OS     |Arch      |File, (Mirror for Chinese Users)                                                                                                                                                                                   |Download Count
:------|:---------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Linux  |32-bit    |[seqkit_linux_386.tar.gz](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_linux_386.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_linux_386.tar.gz))                            |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_linux_386.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_linux_386.tar.gz)
Linux  |**64-bit**|[**seqkit_linux_amd64.tar.gz**](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_linux_amd64.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_linux_amd64.tar.gz))                  |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_linux_amd64.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_linux_amd64.tar.gz)
Linux  |ARM       |[seqkit_linux_arm.tar.gz](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_linux_arm.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_linux_arm.tar.gz))                            |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_linux_arm.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_linux_arm.tar.gz)
OS X   |32-bit    |[seqkit_darwin_386.tar.gz](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_darwin_386.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_darwin_386.tar.gz))                         |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_darwin_386.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_darwin_386.tar.gz)
OS X   |**64-bit**|[**seqkit_darwin_amd64.tar.gz**](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_darwin_amd64.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_darwin_amd64.tar.gz))               |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_darwin_amd64.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_darwin_amd64.tar.gz)
Windows|32-bit    |[seqkit_windows_386.exe.tar.gz](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_windows_386.exe.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_windows_386.exe.tar.gz))          |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_windows_386.exe.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_windows_386.exe.tar.gz)
Windows|**64-bit**|[**seqkit_windows_amd64.exe.tar.gz**](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_windows_amd64.exe.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_windows_amd64.exe.tar.gz))|[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_windows_amd64.exe.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_windows_amd64.exe.tar.gz)
FreeBSD|32-bit    |[seqkit_freebsd_386.tar.gz](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_freebsd_386.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_freebsd_386.tar.gz))                      |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_freebsd_386.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_freebsd_386.tar.gz)
FreeBSD|**64-bit**|[**seqkit_freebsd_amd64.tar.gz**](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_freebsd_amd64.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_freebsd_amd64.tar.gz))            |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_freebsd_amd64.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_freebsd_amd64.tar.gz)
FreeBSD|ARM       |[seqkit_freebsd_arm.tar.gz](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_freebsd_arm.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_freebsd_arm.tar.gz))                      |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_freebsd_arm.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_freebsd_arm.tar.gz)
OpenBSD|32-bit    |[seqkit_openbsd_386.tar.gz](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_openbsd_386.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_openbsd_386.tar.gz))                      |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_openbsd_386.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_openbsd_386.tar.gz)
OpenBSD|**64-bit**|[**seqkit_openbsd_amd64.tar.gz**](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_openbsd_amd64.tar.gz), ([mirror](http://app.shenwei.me/data/seqkit/seqkit_openbsd_amd64.tar.gz))            |[![Github Releases (by Asset)](https://img.shields.io/github/downloads/shenwei356/seqkit/latest/seqkit_openbsd_amd64.tar.gz.svg?maxAge=3600)](https://github.com/shenwei356/seqkit/releases/download/v0.4.2/seqkit_openbsd_amd64.tar.gz)
